# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: xenial
os:
  - linux
  # - osx
julia:
  - 1.0
  - nightly
addons:
  apt:
    packages:
      - python3-pip
matrix:
  include:
    - &tox
      language: python
      env:
        - TOXENV=style
      os: linux
      python: "3.6"
      before_script:
        - pip --version
        - pip install --quiet tox
      script:
        - cd jlm && tox
      after_success: []
    - <<: *tox
      env:
        - TOXENV=type
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
