name = "JuliaManager"
uuid = "0cdbb3b1-e653-5045-b8d5-b31a04c2a6c9"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
